//get all posts
GET http://localhost:8080/todo HTTP/1.1

###

//Add A todo
POST http://localhost:8080/todo/add HTTP/1.1
content-type: application/json

{
    "body": "Todo From Api",
    "authorId": "64b690acfe861323d6a0ebcf"
}
###
//add a user
POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{
    "email": "api@test.com",
    "name" : "test65",
    "password": "testpass"
}